In [1]:
import json
with open('Medical_intent.json',encoding='utf-8') as file:
    data_json=json.load(file)

In [2]:
row=[]
for intent in data_json['intents']:
    tag=intent['tag']
    for pattern in intent['patterns']:
        row.append([pattern,tag])

In [3]:
import pandas as pd
df=pd.DataFrame(row,columns=['Pattern','Tag'])
df

            Pattern       Tag
0                Hi  greeting
1             Hello  greeting
2               Hey  greeting
3           Namaste  greeting
4          Kaise ho  greeting
..              ...       ...
92          See you   goodbye
93        Take care   goodbye
94          Bye bye   goodbye
95  Phir milte hain   goodbye
96       Good night   goodbye

[97 rows x 2 columns]

In [4]:
df.to_csv('Health_chatbot.csv')

In [5]:
data=pd.read_csv('Health_chatbot.csv')
data.head()

   Unnamed: 0   Pattern       Tag
0           0        Hi  greeting
1           1     Hello  greeting
2           2       Hey  greeting
3           3   Namaste  greeting
4           4  Kaise ho  greeting

In [6]:
X=data['Pattern'].str.lower()
Y=data['Tag']

In [7]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
from nltk.stem import WordNetLemmatizer

In [9]:
token=Tokenizer()
token.fit_on_texts(X)
X=token.texts_to_sequences(X)
X=pad_sequences(X)

In [10]:
#instead using label encoder
#y=list(set(Y))
#Y_out=[]
#for i in Y:
 #   Y_out.append(y.index(i))

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()
Y=le.fit_transform(Y)
Y

array([ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  2,  2,  2,  2,  2,  2,  2,  2,  2,  8,  8,  8,  8,  8,  8,  8,
        0,  0,  0,  0,  0,  0,  0,  3,  3,  3,  3,  3,  3,  3,  3,  3, 10,
       10, 10, 10, 10, 10,  5,  5,  5,  5,  5,  5,  5])

In [13]:
#model Building 
model=tf.keras.Sequential([
    layers.Embedding(input_dim=len(token.word_index)+1,output_dim=128),
    layers.LSTM(64),
    layers.Dense(128,activation='relu'),
    layers.Dense(len(le.classes_),activation='softmax')
])

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [16]:
history=model.fit(X,Y,epochs=400,validation_split=0.2)

Epoch 1/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 148ms/step - accuracy: 0.0649 - loss: 2.3958 - val_accuracy: 0.0000e+00 - val_loss: 2.4109
Epoch 2/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2208 - loss: 2.3807 - val_accuracy: 0.0000e+00 - val_loss: 2.4264
Epoch 3/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2857 - loss: 2.3653 - val_accuracy: 0.0000e+00 - val_loss: 2.4495
Epoch 4/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2987 - loss: 2.3470 - val_accuracy: 0.0000e+00 - val_loss: 2.4827
Epoch 5/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2987 - loss: 2.3224 - val_accuracy: 0.0000e+00 - val_loss: 2.5288
Epoch 6/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3117 - loss: 2.2899 - val_accuracy: 0.0000e+00 - val_loss: 2.5994
Epoch 7/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3117 - loss: 2.2522 - val_accuracy: 0.0000e+00 - val_loss: 2.7222
Epoch 8/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2987 - loss: 2.1991 - val_accuracy: 0.0000e+00 - val_loss: 2.9201
Epoch 9/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2987 - loss: 2.1377 - val_accuracy: 0.0000e+00 - val_loss: 3.2066
Epoch 10/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.2597 - loss: 2.0752 - val_accuracy: 0.0000e+00 - val_loss: 3.6040
Epoch 11/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.2597 - loss: 2.0210 - val_accuracy: 0.0000e+00 - val_loss: 4.0344
Epoch 12/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2727 - loss: 1.9608 - val_accuracy: 0.0000e+00 - val_loss: 4.3051
Epoch 13/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3377 - loss: 1.8891 - val_accuracy: 0.0000e+00 - val_loss: 4.4762
Epoch 14/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4935 - loss: 1.8063 - val_accuracy: 0.0000e+00 - val_loss: 4.5816
Epoch 15/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5584 - loss: 1.7197 - val_accuracy: 0.0000e+00 - val_loss: 4.7540
Epoch 16/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6234 - loss: 1.6173 - val_accuracy: 0.0000e+00 - val_loss: 4.9143
Epoch 17/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6494 - loss: 1.4888 - val_accuracy: 0.0000e+00 - val_loss: 5.1412
Epoch 18/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7922 - loss: 1.3569 - val_accuracy: 0.0000e+00 - val_loss: 5.5155
Epoch 19/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8312 - loss: 1.2281 - val_accuracy: 0.0000e+00 - val_loss: 5.8747
Epoch 20/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8442 - loss: 1.0714 - val_accuracy: 0.0000e+00 - val_loss: 6.2608
Epoch 21/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8442 - loss: 0.9259 - val_accuracy: 0.0000e+00 - val_loss: 6.4795
Epoch 22/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8701 - loss: 0.7791 - val_accuracy: 0.0000e+00 - val_loss: 6.6176
Epoch 23/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.6411 - val_accuracy: 0.0000e+00 - val_loss: 6.9561
Epoch 24/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9351 - loss: 0.5264 - val_accuracy: 0.0000e+00 - val_loss: 6.9312
Epoch 25/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9481 - loss: 0.4165 - val_accuracy: 0.0000e+00 - val_loss: 6.8497
Epoch 26/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9481 - loss: 0.3401 - val_accuracy: 0.0500 - val_loss: 7.1108
Epoch 27/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9870 - loss: 0.2520 - val_accuracy: 0.0500 - val_loss: 7.4890
Epoch 28/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9870 - loss: 0.2114 - val_accuracy: 0.0500 - val_loss: 7.4397
Epoch 29/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.1513 - val_accuracy: 0.1000 - val_loss: 7.5052
Epoch 30/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.1239 - val_accuracy: 0.1500 - val_loss: 7.5845
Epoch 31/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0941 - val_accuracy: 0.1500 - val_loss: 7.6656
Epoch 32/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0823 - val_accuracy: 0.1500 - val_loss: 7.7164
Epoch 33/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0573 - val_accuracy: 0.1500 - val_loss: 7.8207
Epoch 34/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0570 - val_accuracy: 0.1500 - val_loss: 7.8892
Epoch 35/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0450 - val_accuracy: 0.1500 - val_loss: 8.0663
Epoch 36/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0356 - val_accuracy: 0.1000 - val_loss: 8.2714
Epoch 37/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0339 - val_accuracy: 0.1000 - val_loss: 8.2080
Epoch 38/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0262 - val_accuracy: 0.1500 - val_loss: 8.1286
Epoch 39/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0237 - val_accuracy: 0.1500 - val_loss: 8.1172
Epoch 40/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0213 - val_accuracy: 0.1500 - val_loss: 8.1755
Epoch 41/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0182 - val_accuracy: 0.1500 - val_loss: 8.2772
Epoch 42/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0170 - val_accuracy: 0.1500 - val_loss: 8.3470
Epoch 43/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0157 - val_accuracy: 0.1500 - val_loss: 8.4162
Epoch 44/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.1500 - val_loss: 8.4022
Epoch 45/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0132 - val_accuracy: 0.1500 - val_loss: 8.4246
Epoch 46/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0121 - val_accuracy: 0.1500 - val_loss: 8.4976
Epoch 47/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0113 - val_accuracy: 0.1500 - val_loss: 8.5144
Epoch 48/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0107 - val_accuracy: 0.1500 - val_loss: 8.5159
Epoch 49/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.0101 - val_accuracy: 0.1500 - val_loss: 8.5293
Epoch 50/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 0.1500 - val_loss: 8.5660
Epoch 51/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0090 - val_accuracy: 0.1500 - val_loss: 8.5764
Epoch 52/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.1500 - val_loss: 8.5668
Epoch 53/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.1500 - val_loss: 8.5621
Epoch 54/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 0.1500 - val_loss: 8.5552
Epoch 55/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.0075 - val_accuracy: 0.1500 - val_loss: 8.5726
Epoch 56/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0072 - val_accuracy: 0.1500 - val_loss: 8.5934
Epoch 57/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.1500 - val_loss: 8.6381
Epoch 58/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.0065 - val_accuracy: 0.1500 - val_loss: 8.6754
Epoch 59/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.1500 - val_loss: 8.6657
Epoch 60/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.1500 - val_loss: 8.6437
Epoch 61/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.0059 - val_accuracy: 0.1500 - val_loss: 8.6335
Epoch 62/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.1500 - val_loss: 8.6513
Epoch 63/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.1500 - val_loss: 8.6767
Epoch 64/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.1500 - val_loss: 8.6879
Epoch 65/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.1500 - val_loss: 8.7052
Epoch 66/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.1500 - val_loss: 8.7175
Epoch 67/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.1500 - val_loss: 8.7368
Epoch 68/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.1500 - val_loss: 8.7581
Epoch 69/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.1500 - val_loss: 8.7440
Epoch 70/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.1500 - val_loss: 8.7456
Epoch 71/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.1500 - val_loss: 8.7504
Epoch 72/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.1500 - val_loss: 8.7659
Epoch 73/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.1500 - val_loss: 8.7894
Epoch 74/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.1500 - val_loss: 8.7836
Epoch 75/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.1500 - val_loss: 8.7746
Epoch 76/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.1500 - val_loss: 8.8106
Epoch 77/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.1500 - val_loss: 8.8458
Epoch 78/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.1500 - val_loss: 8.8634
Epoch 79/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.1500 - val_loss: 8.8502
Epoch 80/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.1500 - val_loss: 8.8516
Epoch 81/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.1500 - val_loss: 8.8597
Epoch 82/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.1500 - val_loss: 8.8762
Epoch 83/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.1500 - val_loss: 8.8821
Epoch 84/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.1500 - val_loss: 8.8775
Epoch 85/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.1500 - val_loss: 8.8796
Epoch 86/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.1500 - val_loss: 8.8860
Epoch 87/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.1500 - val_loss: 8.8897
Epoch 88/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.1500 - val_loss: 8.8973
Epoch 89/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.1500 - val_loss: 8.9245
Epoch 90/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.1500 - val_loss: 8.9445
Epoch 91/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.1500 - val_loss: 8.9673
Epoch 92/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.1500 - val_loss: 8.9516
Epoch 93/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.1500 - val_loss: 8.9459
Epoch 94/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.1500 - val_loss: 8.9479
Epoch 95/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.1500 - val_loss: 8.9377
Epoch 96/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.1500 - val_loss: 8.9292
Epoch 97/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.1500 - val_loss: 8.9239
Epoch 98/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.1500 - val_loss: 8.9406
Epoch 99/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.1500 - val_loss: 8.9708
Epoch 100/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.1500 - val_loss: 9.0081
Epoch 101/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.1500 - val_loss: 9.0289
Epoch 102/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.1500 - val_loss: 9.0197
Epoch 103/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.1500 - val_loss: 9.0108
Epoch 104/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.1500 - val_loss: 9.0117
Epoch 105/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.1500 - val_loss: 9.0057
Epoch 106/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.1500 - val_loss: 9.0188
Epoch 107/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.1500 - val_loss: 9.0401
Epoch 108/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.1500 - val_loss: 9.0719
Epoch 109/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.1500 - val_loss: 9.0917
Epoch 110/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.1500 - val_loss: 9.1015
Epoch 111/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.1500 - val_loss: 9.0919
Epoch 112/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.1500 - val_loss: 9.0675
Epoch 113/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.1500 - val_loss: 9.0557
Epoch 114/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.1500 - val_loss: 9.0544
Epoch 115/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.1500 - val_loss: 9.0678
Epoch 116/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.1500 - val_loss: 9.0800
Epoch 117/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.1500 - val_loss: 9.0865
Epoch 118/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.1500 - val_loss: 9.1037
Epoch 119/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.1500 - val_loss: 9.1080
Epoch 120/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.1500 - val_loss: 9.1133
Epoch 121/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.1500 - val_loss: 9.1135
Epoch 122/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.1500 - val_loss: 9.1119
Epoch 123/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.1500 - val_loss: 9.1101
Epoch 124/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.1500 - val_loss: 9.1135
Epoch 125/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.1500 - val_loss: 9.1128
Epoch 126/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.1500 - val_loss: 9.1203
Epoch 127/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.1500 - val_loss: 9.1261
Epoch 128/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1386
Epoch 129/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1460
Epoch 130/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1543
Epoch 131/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1531
Epoch 132/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1529
Epoch 133/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.1500 - val_loss: 9.1406
Epoch 134/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1362
Epoch 135/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1393
Epoch 136/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1415
Epoch 137/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1484
Epoch 138/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1651
Epoch 139/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.1500 - val_loss: 9.1764
Epoch 140/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.1500 - val_loss: 9.1844
Epoch 141/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.1500 - val_loss: 9.1816
Epoch 142/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.1500 - val_loss: 9.1802
Epoch 143/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.1500 - val_loss: 9.1756
Epoch 144/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 9.8686e-04 - val_accuracy: 0.1500 - val_loss: 9.1849
Epoch 145/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 9.7355e-04 - val_accuracy: 0.1500 - val_loss: 9.1936
Epoch 146/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 9.6026e-04 - val_accuracy: 0.1500 - val_loss: 9.1977
Epoch 147/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 9.4867e-04 - val_accuracy: 0.1500 - val_loss: 9.2037
Epoch 148/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 9.3549e-04 - val_accuracy: 0.1500 - val_loss: 9.2105
Epoch 149/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 9.2385e-04 - val_accuracy: 0.1500 - val_loss: 9.2250
Epoch 150/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 9.1019e-04 - val_accuracy: 0.1500 - val_loss: 9.2305
Epoch 151/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 8.9958e-04 - val_accuracy: 0.1500 - val_loss: 9.2266
Epoch 152/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 8.8474e-04 - val_accuracy: 0.1500 - val_loss: 9.2183
Epoch 153/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 8.7347e-04 - val_accuracy: 0.1500 - val_loss: 9.2136
Epoch 154/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 8.6252e-04 - val_accuracy: 0.1500 - val_loss: 9.2206
Epoch 155/400
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 8.5329e-04 - val_accuracy: 0.1500 - val_loss: 9.2286
Epoch 156/400

In [17]:
max_len=X.shape[1]
max_len

5

In [18]:
import numpy as np
def predict(pred):
    pred=pred.lower()
    pred=token.texts_to_sequences([pred])
    pred=pad_sequences(pred,maxlen=max_len)
    Y_pred=model.predict(pred)
    print(Y_pred)
    index=np.argmax(Y_pred)
    tag=le.inverse_transform([index])
    print(tag,index)
predict('hello')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step
[[3.9259742e-09 5.6397383e-08 1.3553473e-07 7.6812366e-06 2.3561486e-06
  1.2482808e-09 9.9989748e-01 3.3459673e-05 1.3545230e-07 5.8736667e-05
  1.2013296e-10]]
['greeting'] 6

In [19]:
model.save('Health_chatbot.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [20]:
import os
os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'chatbot.jpg',
 'Healthcare_chatbot.ipynb',
 'Health_chatbot.csv',
 'Health_chatbot.h5',
 'label.pkl',
 'max_len.pkl',
 'Medical_intent.json',
 'token.pkl']

In [21]:
import joblib
joblib.dump(le,'label.pkl')
joblib.dump(token,'token.pkl')
joblib.dump(max_len,'max_len.pkl')

['max_len.pkl']